---
version: '2'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql